t/60-autoqc-autoqc.t, t/60-autoqc-qc_store.t, t/60-autoqc-results-collection.t, t/data/.npg/npg_tracking
by providing npg_tracking config in test via HOME directory env var
reset so that paths in tests match those expected
https://github.com/wtsi-npg/npg_tracking/pull/254
=> Cope with config file (instead of code) based config of npg_tracking

Build.PL, lib/npg_qc/autoqc/checks/gc_fraction.pm, lib/npg_qc/autoqc/checks/ref_match.pm, lib/npg_qc/autoqc/checks/sequence_error.pm
Depends on https://github.com/wtsi-npg/npg_tracking/pull/265
Ensures that local path is not captures in the autoqc results objects.
=> use network path instead of a local path for ref repository dependant path

Changes, bin/gtck_extract_fluidigm_data_from_irods.sh, bin/gtck_genplexlist.sh, bin/gtck_refresh_check_data.sh, bin/reformat_fluidigm_snp26_results_irods.pl
updated scripts to fail more readily and informatively when an iRODS error occurs.
Used 'set -e' in the top level gtck_refresh_data.sh script and 'set -o pipefail' with explicit checks for error return in (bash) subscripts. If the reformat_fluidigm_snp26_results_irods.pl perl script sees the "error" attribute in its incoming JSON data stream from baton-get, it reports the first 64 occurrences then croaks after reading the full input stream to avoid a potential blizzard of "broken pipe" errors from an iRODS client supplying the data. Used the '--silent' flag for baton-get since it otherwise replicates to stderr the content of error messages in its JSON output (which will be reported by the reformat_fluidigm_snp26_results_irods.pl script).
=> genotype check data extraction scripts, iRODS errors

Changes, lib/npg_qc/Schema/Mqc/OutcomeEntity.pm, lib/npg_qc/Schema/Result/MqcOutcomeEnt.pm, npg_qc_viewer/lib/npg_qc_viewer/Controller/Mqc.pm, scripts/mqc/import_seqqcape_mqc_outcomes, t/50-schema-result-MqcLibraryOutcomeEnt.t, t/50-schema-result-MqcOutcomeEnt.t
- script to import manual qc values from the old warehouse RT#493757
- update_outcome method of mqc entities renamed to update_nonfinal_outcome
- a new update_outcome method allows for update of final outcomes
- method to toggle stored final manual qc outcomes
New ways to update are needed in order to be able to maintain the oucomes via scripts after these outcomes were finalised during the mqc process.
For example, to toggle the outcome
perl -le 'use npg_qc::Schema; my $rs=npg_qc::Schema->connect()->resultset("MqcOutcomeEnt"); $row=$rs->search({id_run=>XXX, position=>4})->next; print $row->mqc_outcome->short_desc; $row->toggle_final_outcome("some user", "RT#YYY"); print $row->mqc_outcome->short_desc'
Rejected final
Accepted final
=> mqc outcomes - more ways to update

npg_qc_viewer/README
Updating documentation to reflect new path of bower.json when using bower link
=> New path for bower.json when using bower link

npg_qc_viewer/t/80-app-run.t
Our building procedure injects the latest git tag into the source code. The tag is used to generate the version which appears in the title (as in html title) and text of the page. If there is no final tag assigned, a string is generated and used as proxy for the tag.
In this case the string generated and inserted in the page in jenkins was:
0.0-jenkins-npg-qc-wtsi-devel-**152**3
So it was being injected into the html.
The test modified in this commit has some checks for number of cycles which should be in some pages but not in others. The number of cycles is **152** from fixtures. Because the test was blindly checking the html source for 152 it was finding it as a substring of the title.
Using a larger sample reduces the chances of random occurrences for the future.
=> Using larger page sample for mech to check

Changes, npg_qc_viewer/Build.PL
Force latest version when finding conflicts with packages versions. Conflict may arise when updating a previously installed stack.
=> Bower force latests when in conflict

.travis.yml
Recent release of mysql (5.7.14) breaks our builds. Until version can be fixed to 5.7.13 use default travis mysql to keep CI working
=> introduce regresion to default mysql until fix

Build.PL, Changes, lib/npg_qc/autoqc/checks/genotype.pm
Made building the iRODS handle of npg_qc::autoqc::checks::genotype lazy to avoid calling baton until required at runtime.
Added WTSI::NPG::iRODS to Build.PL extended_requires.
=> Made building the iRODS handle of npg_qc::autoqc::checks::genotype lazy

Changes, npg_qc_viewer/Build.PL
- build will die if node or bower or npm are not available in the path
=> change behaviour of build regarding node tools

t/60-autoqc-checks-genotype.t
Pass instance of WTSI::NPG::iRODS to npg_qc::autoqc::checks::genotype constructor during tests.
=> Pass instance of WTSI::NPG::iRODS during tests

Build.PL
Allow samtools source code location to be declared with SAMTOOLS_SOURCE_PATH and htslib install prefix to be declared with HTSLIB_INSTALL_PATH (the latter for consistency - it will be detected in most cases).
=> Allow samtools source code location to be declared

.travis.yml, Changes
Because otherwise they will move use by default to trusty
https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
=> use explicit dist in travis yml

Changes, MANIFEST, lib/npg_qc/Schema/ResultSet.pm, lib/npg_qc/autoqc/db_loader.pm, t/50-schema-result-SeqComposition.t, t/50-schema-resultset.t, t/60-autoqc-db_loader.t
... because we need a factory method for db-based compositions, which can be used elsewhere (in migration of all autoqc tables to compositions).  Lots of tests as well.
=> Autoqc dbloader refactoring

Changes, lib/npg_qc/Schema/ResultSet/MqcOutcomeEnt.pm, t/50-schema-resultset-MqcOutcomeEnt.t
Without thi sfix we have the following failure
died: Moose::Exception::SingleParamsToNewMustBeHashRef (Single parameters to new() must be a HASH ref at constructor npg_qc::Schema::ResultSet::MqcOutcomeEnt::new (defined at /nfs/users/nfs_m/mg8/working/npg_qc/blib/lib/npg_qc/Schema/ResultSet/MqcOutcomeEnt.pm line 32) line 11
npg_qc::Schema::ResultSet::MqcOutcomeEnt::new('npg_qc::Schema::ResultSet::MqcOutcomeEnt', 'DBIx::Class::ResultSource::Table=HASH(0x6f082b0)') called at /software/npg/20170908/lib/perl5/DBIx/Class/ResultSet.pm line 3389
DBIx::Class::ResultSet::as_subselect_rs('npg_qc::Schema::ResultSet::MqcOutcomeEnt=HASH(0x7eb4650)') called at /software/npg/20170908/lib/perl5/DBIx/Class/ResultSet.pm line 1766
DBIx::Class::ResultSet::_count_subq_rs('npg_qc::Schema::ResultSet::MqcOutcomeEn …
=> fix resultset constructor

Changes, MANIFEST, lib/npg_qc/autoqc/checks/bam_flagstats.pm, t/60-autoqc-checks-bam_flagstats.t, t/60-autoqc-db_loader.t, t/data/autoqc/bam_flagstats/24135_1#1.bam_flagstats.json, t/data/autoqc/bam_flagstats/24135_1#1.flagstat
- option to run without markdups metrics file 
- some metrics e.g. paired_mapped_reads, previously generated from markdups metrics now generated from flagstat file (so will include qc fail reads as other existing flagstat metrics)
=>  update bam_flagstats to support no markdups option

Build.PL
C utilities have been moved to a separate package https://github.com/wtsi-npg/npg_qc_utils and will be compiled separately. For time being will build as before on existing clusters.
=> compile fastq_summ on Ubuntu Precise only

lib/npg_qc/autoqc/checks/spatial_filter.pm, lib/npg_qc/autoqc/results/spatial_filter.pm, t/data/autoqc/25830_1#1.filter.stats, t/data/autoqc/25830_1#2.filter.stats, t/data/autoqc/25830_1#3.filter.stats
change spatial_filter check to use input_files attribute; parse files looking for entries for the specified id_run and position (derived from composition), summing the "Processed" and "Failed" values over the lane
=> change spatial_filter check to use input_files attribute

bin/npg_qc_save_files.pl, lib/npg_qc/file_store.pm, t/10-file_store.t
The naming convention for fastqcheck plex-level files has changed, the location of these files in the run folder has changed and we will soon not need these files anyway, so went for a simple option.
However, we will lose q30 and q40 yeilds on plex level in the warehouse. We are going to extend qx yield autoqc check to capture those and then load to the wh. Meanwhile, this pr should wait.
=> limit fastqcheck files saved to lane-level files only

Build.PL, Changes, MANIFEST, lib/npg_qc/autoqc/checks/check.pm, lib/npg_qc/autoqc/checks/spatial_filter.pm, t/60-autoqc-checks-spatial_filter.t
use search directory to locate spatial_filter.stats files instead of an explicit list of input files (unworkable with highly plexed lanes)
=> spatial_filter check input spec change

lib/npg_qc/autoqc/qc_store.pm, t/60-autoqc-qc_store.t
This is a comprehensive reimplementation of the qc data loader for staging area. The existing version has a bug that does not allow to load files in directories for partial merges (example: lane1-2) and also considered cases with merged and unmerged files as mutually exclusive. This implementation is also easier to follow.
=> comprehensive staging area loader

lib/npg_qc/autoqc/role/ref_match.pm, npg_qc_viewer/root/src/ui_checks/ref_match.tt2, npg_qc_viewer/root/src/ui_lanes/lane.tt2, t/60-autoqc-results-ref_match.t
To optimise loading of the ml warehouse, we need deterministic top two matches
=> Deterministic ref match organism sort

Changes, npg_qc_viewer/root/src/ui_checks/checks_in_full.tt2, npg_qc_viewer/root/static/scripts/collapse.js
Breaking change in template caused collapse to ignore divs
where check was marked as passed or failed.
=> fix regular expression in collapse.js

bin/npg_simple_robo4artic
Previously I filtered out the header with grep before piping into the script. Does not work in the pipeline if artic's QC summary file is empty.
=> filter out artic header

Build.PL, Changes, bin/npg_simple_robo4artic, lib/npg_qc/autoqc/results/base.pm
Reg expressions for negative and positive controls have to be re-checked and, possibly, extended
=> add robo (mqc) for negative controls

Changes, bin/npg_autoqc_generic4artic
`$g->result->doc->{meta}->{num_input_reads} `was missing in the result object because the hash ref assigned to `$g->result->doc->{meta}` was overwritted by `$g->result->doc->{'meta'} = $g->get_sample_info();`
Now the order of the assignments is reversed.
=> bug fix for the order of assignment of keys

Changes, bin/genotype_call_results_reporter, lib/npg_qc/report/genotype_call.pm, t/70-report-genotype_call.t
It's likely PSD will only utilise results from human QC plexes within SM and therefore adding an option so only those results can be posted back to their API.
=> add gbs_plex option to genotype_call_results_reporter

lib/npg_qc/autoqc/qc_store.pm, lib/npg_qc/autoqc/role/ref_match.pm
... when getting data for each QC result type. Saves ten seconds on page load for on a sample run_id
=> Add a prefetch for composition components

.github/workflows/testing_and_building_repos.yml, scripts/before_install.sh
There is not much choice of Node.js versions in the Conda defaults channel. I've used the only one that is LTS (EOL 2023-04-30)
=> Add Node.js version build matrix

npg_qc_viewer/package.json
New versions of NPM reformat the file automatically. Perl generates a dirty tag
for the version if the file is not committed with the expected format applied
beforehand.
=> reformat package.json

Build.PL, Changes, lib/npg_qc/autoqc/checks/gc_fraction.pm
The package has been moved to an internal git repository and is no
longer available for the CI builds.
Resolves https://github.com/wtsi-npg/npg_qc/issues/757
=> Remove dependency on npg_common::sequence::reference::base_count

lib/npg_qc/autoqc/checks/generic.pm, lib/npg_qc/autoqc/results/generic.pm, t/60-autoqc-checks-generic-artic.t, t/60-autoqc-checks-generic.t, t/60-autoqc-results-generic.t
Extended set_pp_info() method in npg_qc::autoqc::results::generic.
Added an optional third argument - portable pipewline repository URL,
which is saved in the object's info attribute.
Added an optional attribute pp_url to npg_qc::autoqc::checks::generic.
Extended the set_common_result_attrs() of the check object to pass
the value of the new attribute to the generic result object.
=> Ability to set and save information about the pp url.     

Changes, bin/npg_mqc_skipper
Use entity_type in the iseq_flowcell table to exclude spiked-in
controls. The change is driven by the fact that spiked-in controls
can now belong to a number of different studies.
Achieves the same result as https://github.com/wtsi-npg/npg_qc/pull/773, but is more generic
=> mqc skipper - a generic way to disregard spiked-in controls

Changes, lib/npg_qc/Schema/Result/Adapter.pm, lib/npg_qc/Schema/Result/QXYield.pm, scripts/upgrade_schema/upgrade_schema-69.9.0
Change database column type from unsigned int to unsigned bigint
for columns where we store number of reads and similar values and
where we do not already set type to bigint. Some NovaSeq runs
produce more data than we envisaged when these tables were set up.
The schema update will be tested on the replica of the production database
to get an idea of how long the update takes.
=> Archive QC data for runs with large number of reads.

Changes, npg_qc_viewer/bower.json, npg_qc_viewer/package.json
Github dropped support for unauthenticated git protocol pulls, [see](https://web.archive.org/web/20220322001054/https://github.blog/2021-09-01-improving-git-protocol-security-github/).
The change seems was final on 20220315, so we would need to change those git urls to https equivalents to be able to pull from the repos without authenticating.
=> Bower url dependencies update

scripts/npgqc_dbix_schema_loader.pl
Clean-up in npg_qc DB means these exclusions have lost their meaning and can be removed.
=> Simplify schema exclusions now the tables are gone

Changes, lib/npg_qc/autoqc/checks/rna_seqc.pm
Small fix until we add an argument for the check to control the number.
=> rna seq qc max memory increased to 8GB

Changes, npg_qc_viewer/root/src/ui_lanes/lane.tt2
The was intruduced while updating the SeqQC summary display for pulldown_metrics incomplete results. The bug manifestation is a display appearence of an
unexpected raw mean depth value just before the coverage value.
=> Fixed the SeqQC pulldown metrics display bug

bin/npg_qc_tag_sniff.pl
If the same sequence is seen in both index reads, which can happen if some of the expected i7 tags are the reverse compliment of some of the i5 tags or vice versa, the reported matches can be from the wrong index read
=> handle cases where the same tag sequence is seen in both index reads

.gitlab-ci.yml, Changes, docs/CtoA_substitution_metrics.md, docs/includes/repo-metadata.md, docs/qc_outcomes_change_howto.md
This change is to enable automatic update of [NPG confluence](https://ssg-confluence.internal.sanger.ac.uk/pages/viewpage.action?pageId=153044872#) page.
=> Automatic confluence update

bin/elembio_runstats_parser.pl
Add a parameter that specifies the url to elembio qc report in the `tag_metrics` file
=> Add elembio qc report url to tag_metrics file

Changes, lib/npg_qc/elembio/sample_stats.pm, lib/npg_qc/elembio/tag_metrics_generator.pm, t/30-elembio-runstats.t
Control samples are identified by their name and flagged. Examples: GCACATAGTC-GACTACTAGC(CTRL) or
ATGTCGCTAG-CTAGCTCGTA[+3](CTRL).
Where there is one control sample per lane, spiked_control_index attribute of npg_qc::autoqc::results::tag_metrics objectis set, making calculations of the coefficient of variance and highlighting of underrepresented tags more accurate.
=> Identification of sequencing controls.
