wtsi-npg/npg_qc

Changes, npg_qc_viewer/Build.PL
and, optionally, set up a link to bcviz
=> extend SeqQC build file to deploy all app files

Build.PL, src/norm_fit/Makefile
Pul object files and teh executable into a separate directory so that git does not mark the version is dirty after making normfit
=> improved makefile for normfit

Changes, lib/npg_qc/Schema/Result/MqcOutcomeDict.pm, lib/npg_qc/Schema/Result/MqcOutcomeEnt.pm, lib/npg_qc/Schema/ResultSet/MqcOutcomeEnt.pm, t/50-schema-result-MqcOutcomeDict.t, t/50-schema-result-MqcOutcomeEnt.t
Adding methods to encapsulate the is_accepted and is_final_accepted logic in the models.
=> Dev mqc temp qc status

lib/npg_qc/Schema/ResultSet/MqcOutcomeEnt.pm
Fixing a documentation which failed for POD check.
=> Fixing POD method name error which caused podcheck fail.

Changes, lib/npg_qc/autoqc/results/collection.pm, lib/npg_qc/illumina/loader/Run_Caching.pm, t/30-illumina-loader-Bustard_Summary.t, t/30-illumina-loader-Cluster_Density.t, t/30-illumina-loader-Matrix.t, t/30-illumina-loader-Offset.t, t/30-illumina-loader-Recipe.t, t/30-illumina-loader-Run_Caching.t, t/30-illumina-loader-Runinfo.t, t/30-illumina-loader-Signal_Mean.t, t/30-illumina-loader-base.t, t/30-illumina-loader.t, t/60-autoqc-db_loader.t, t/60-autoqc-results-collection.t
depends on https://github.com/wtsi-npg/npg_tracking/pull/261
=> no access to user home directory in db tests & plex fork in SeqQC for old data

Changes, lib/npg_qc/autoqc/checks/gc_bias.pm, t/60-autoqc-checks-check.t, t/60-autoqc-checks-sequence_error.t, t/70-autoqc-checks-check.t
which are failing following cleanup of unused methods
=> remove vestigial tests & skip gc_bias if missing window_depth

Changes, bin/gtck_combine_gt_data.sh, bin/gtck_extract_fluidigm_data_from_irods.sh, bin/gtck_genplexlist.sh, bin/gtck_install_to_repos.sh, bin/gtck_refresh_check_data.sh, bin/reformat_fluidigm_snp26_results_irods.pl
Added a set of scripts so that creation of genotype check data can be done via a cronjob. Dependency on baton tools.
=> Autoqc genotype check data prep scripts

Changes, bin/gtck_combine_gt_data.sh, bin/gtck_extract_fluidigm_data_from_irods.sh, bin/gtck_genplexlist.sh, bin/gtck_install_to_repos.sh, bin/gtck_refresh_check_data.sh, bin/reformat_fluidigm_snp26_results_irods.pl, src/gt_utils/gt_pack.c
update scripts for genotype check data preparation (perlcritic issues and version strings)
gt_pack recognises version 02 headers in append mode
=> Autoqc genotype check data prep scripts update

Changes, bin/gtck_combine_gt_data.sh, bin/gtck_extract_fluidigm_data_from_irods.sh, bin/gtck_genplexlist.sh, bin/gtck_install_to_repos.sh, bin/gtck_refresh_check_data.sh, bin/reformat_fluidigm_snp26_results_irods.pl
Update genotype check data prep scripts to be configurable with environment variables (iRODS zones and installation target directories)
=> Autoqc genotype check data prep scripts multizone

npg_qc_viewer/root/src/ui_checks/checks_in_full.tt2
=> gc bias back

.travis.yml, .travis/before_install.sh, .travis/install.sh, .travis/script.sh, Build.PL, Changes, bin/npg_qc_tag_sniff.pl, npg_qc_viewer/root/static/test/test.js, t/50-schema-result-MqcLibraryOutcomeEnt.t, t/50-schema-result-MqcOutcomeEnt.t, t/50-schema-result-SamtoolsStats.t, t/50-schema-result-SequenceSummary.t, t/60-autoqc-results-bam_flagstats.t, t/60-autoqc-results-samtools_stats.t, t/60-autoqc-results-sequence_summary.t
This PR is currently for information only. Please don't merge yet.
=> Travis perl rc

t/60-autoqc-qc_store.t
Forward compatibility with https://github.com/wtsi-npg/npg_tracking/pull/320 - need to make proper $self available for the method.
=> use test db object

Changes, npg_qc_viewer/lib/npg_qc_viewer/Util/TransferObject.pm, npg_qc_viewer/lib/npg_qc_viewer/Util/TransferObjectFactory.pm, npg_qc_viewer/t/10-util-TransferObject.t
No lims data - no manuak qc. This will also help with GCLP, ie no chance of displaying manual qc widgets for GCLP libraries.
=> no mqc widgets if lims data not available

.travis.yml, .travis/before_install.sh, .travis/script.sh, Changes, npg_qc_viewer/bower.json
- Updating nvm
- Using a matrix to test using nodejs v4.4.2 and 0.12.9
- Setting bower@1.7.9
=> Bump bower 1604

.gitignore, .travis/script.sh, Changes, npg_qc_viewer/.jscsrc, npg_qc_viewer/.jshintrc, npg_qc_viewer/Build.PL, npg_qc_viewer/Gruntfile.js, npg_qc_viewer/MANIFEST, npg_qc_viewer/README, npg_qc_viewer/package.json, npg_qc_viewer/t/client/run_js_tests.sh, npg_qc_viewer/t/client/test.html, npg_qc_viewer/t/client/test.js, npg_qc_viewer/t/client/test_collapser.js, npg_qc_viewer/t/client/test_format_for_csv.html, npg_qc_viewer/t/client/test_format_for_csv.js, npg_qc_viewer/t/client/test_modify_on_view.html, npg_qc_viewer/t/client/test_modify_on_view.js, npg_qc_viewer/t/client/test_qc_outcomes_view.html, npg_qc_viewer/t/client/test_qc_outcomes_view.js, npg_qc_viewer/t/client/test_qc_page.html, npg_qc_viewer/t/client/test_qc_page.js, npg_qc_viewer/t/client/test_qc_utils.html, npg_qc_viewer/t/client/test_qc_utils.js
Updating test configuration so is compatible with phantom wrappers
Using Grunt to automate tasks (code linting and tests)
Updating Build.PL so it also deploys node deps before bower deps
=> Updating tests and using Grunt

npg_qc_viewer/Gruntfile.js, npg_qc_viewer/README, npg_qc_viewer/root/static/scripts/collapse.js
Modify test task so now it can take a parameter with file glob to run subset of files
eg
grunt test:*collap*.html
=> Grunt run test with file pattern

Changes, bin/qc, lib/npg_qc/autoqc/autoqc.pm, lib/npg_qc/autoqc/checks/check.pm, lib/npg_qc/autoqc/checks/qX_yield.pm, t/60-autoqc-autoqc.t, t/60-autoqc-checks-af_metrics.t, t/60-autoqc-checks-check.t, t/60-autoqc-checks-gc_fraction.t, t/60-autoqc-checks-genotype.t, t/60-autoqc-checks-pulldown_metrics.t, t/60-autoqc-checks-qX_yield.t, t/60-autoqc-checks-sequence_error.t, t/60-autoqc-checks-tag_metrics.t, t/60-autoqc-checks-tags_reporters.t, t/60-autoqc-checks-upstream_tags.t, t/60-autoqc-results-upstream_tags.t, t/80-autoqc-qc-script.t
To be tested within the pipeline
=> arbitrary qc script args

Changes, npg_qc_viewer/Build.PL, npg_qc_viewer/MANIFEST, npg_qc_viewer/lib/npg_qc_viewer/Controller/Illumina.pm, npg_qc_viewer/root/src/ui_illuminaqc/summary.tt2, npg_qc_viewer/root/src/ui_runs/run_menu.tt2, npg_qc_viewer/t/40-controller-Illumina.t, npg_qc_viewer/t/perlcriticrc
Data are retrieved from mlwarehouse.
Needs tests.
=> SeqQC replacement for NPG_QC pages

t/10-model-cache_query.t
Sometimes results are returned as 0, sometimes as 0.00
=> test copes with loss of precision for zero values

Changes, lib/npg_qc/autoqc/role/contamination.pm, t/60-autoqc-results-contamination.t
for the old contamination check.
Needed by https://github.com/wtsi-npg/npg_ml_warehouse/pull/64
=> reduce uncertainty in ranking close results

Build.PL, Changes
see also https://github.com/wtsi-npg/npg_tracking/pull/374
=> ClearPress version pinned

.travis.yml
Fixed originally proposed by @keithj
=> travis fix for iRODS

t/60-autoqc-checks-genotype.t
to allow smoother development flow
=> reduce strictness version checks for tests

.travis.yml, t/60-autoqc-checks-rna_seqc.t
Cope with https://github.com/wtsi-npg/npg_tracking/pull/403
=> tweak test to accomodate removal of unused 'subset' attribute in ref tracking

Build.PL, lib/npg_qc/autoqc/checks/check.pm
Use a factory class to define rpt_list attribute and composition computation
Depends on https://github.com/wtsi-npg/npg_tracking/pull/421
=> refactor autoqc checks parent object

npg_qc_viewer/t/40-controller-QcOutcomes.t, t/60-autoqc-checks-check.t
depends on https://github.com/wtsi-npg/npg_tracking/pull/425
=> reflect change in error message in parsing rpt strings

Changes
merge master back to devel after patch release
=> refresh devel after 64.4.1 patch

Changes, lib/npg_qc/Schema/Mqc/OutcomeEntity.pm, lib/npg_qc/Schema/Result/UqcOutcomeEnt.pm, lib/npg_qc/mqc/outcomes.pm, npg_qc_viewer/t/40-controller-QcOutcomes.t, t/50-schema-result-UqcOutcomeEnt.t, t/70-mqc-outcomes.t
This pull request is based on https://github.com/wtsi-npg/npg_qc/pull/488, it replaces https://github.com/wtsi-npg/npg_qc/pull/485 and https://github.com/wtsi-npg/npg_qc/pull/487
Might require more tests for npg_qc::mqc::outcomes
=> Uqc save and update

lib/npg_qc/autoqc/checks/insert_size.pm, lib/npg_qc/autoqc/checks/qX_yield.pm, t/60-autoqc-checks-insert_size.t, t/60-autoqc-checks-qX_yield.t, t/80-autoqc-qc-script.t
Will require a small pipeline patch
=> autoqc checks - remove dependency on tracking XML

lib/npg_qc/autoqc/checks/upstream_tags.pm
use standard samtools command accessor
remove other unused code
Tested by running a check and comparing to prod results
=> remove vestiges of decoding with BamIndexDecoder.jar

Build.PL, npg_qc_viewer/Build.PL
and use WTSI::DNAP::Utilities::Build as a base
=> remove unused functionality in Build.PL

Changes, lib/npg_qc/autoqc/checks/check.pm, lib/npg_qc/autoqc/results/collection.pm, lib/npg_qc/autoqc/role/result.pm, lib/npg_qc/autoqc/role/rpt_key.pm, npg_qc_viewer/root/src/ui_lanes/library_lanes.tt2, t/60-autoqc-results-collection.t, t/60-autoqc-results-result.t
Display of heatmaps is outstanding (work is being done in a different branch). The absence of maps does not break anything, so the pr is meargeble, especially if we are to have an early demo of the new functionality.
=> SeqQC display for merges

Changes, lib/npg_qc/autoqc/role/rpt_key.pm, lib/npg_qc/mqc/outcomes.pm, npg_qc_viewer/lib/npg_qc_viewer/Controller/Checks.pm, npg_qc_viewer/lib/npg_qc_viewer/Model/MLWarehouseDB.pm, npg_qc_viewer/lib/npg_qc_viewer/Util/TransferObjectFactory.pm, npg_qc_viewer/root/src/ui_lanes/library_lanes.tt2, npg_qc_viewer/root/static/scripts/qcoutcomes/manual_qc.js, npg_qc_viewer/root/static/scripts/qcoutcomes/manual_qc_ui.js, npg_qc_viewer/root/static/scripts/qcoutcomes/qc_outcomes_view.js, npg_qc_viewer/root/static/scripts/qcoutcomes/qc_utils.js, npg_qc_viewer/t/10-util-TransferObjectFactory.t, npg_qc_viewer/t/20-model-MLWarehouseDB.t, npg_qc_viewer/t/40-controller-QcOutcomes.t, npg_qc_viewer/t/80-app-run.t, npg_qc_viewer/t/client/test.js, npg_qc_viewer/t/client/test_fixtures.js, t/50-schema-resultset.t, t/60-autoqc-role-rpt_key.t, t/70-mqc-outcomes.t
Manual QC GUI was tested against dev system both for production runs and for one of test runs with merged data.
=> manual QC for multi-comp entities

MANIFEST, lib/npg_qc/autoqc/qc_store.pm, lib/npg_qc/autoqc/qc_store/query_non_tracking.pm, t/60-autoqc-qc_store-query.t
... to be used in npg_qc::autoqc::db_loader
Also a method to read a JSON file and return a result object made public to be used in the db loader
=> method to retrieve autoqc data from a given archive directory

npg_qc_viewer/t/data/fixtures/npg/000-RunStatusDict.yml, t/data/fixtures/npg_tracking/000-run_status_dict.yml
... on temporal_index in run_status_dict (tracking db)
Linked to https://github.com/wtsi-npg/npg_tracking/pull/493
=> db fixtures update to satisfy unique not null constraint

lib/npg_qc/autoqc/qc_store.pm, t/60-autoqc-qc_store.t
Ensure that qc_store does not return results that only partially belong to the requested run, ie
are for merged entities where some components belong to a different run.
The code is heavily refactored to channel two methods of querying the database via the same private method that retrieves results for all eligible compositions at once.
The method that is used by the SeqQC viewer and the wh loader is optimised so that all logic about how to search is applied once to seq_composition table rather than to each individual autoqc table as it was before. Once all compositions are found, s simple single query is made on individual tables to retrieve the results.
SeqQC viewer tested with this code. Loading a page for 300 plexes is not slower than the prod version. The wh loader tests run OK.
=> refactor retrieval of autoqc results for a run from a db

Changes, lib/npg_qc/autoqc/checks/adapter.pm, t/60-autoqc-checks-adapter.t
Goes together with https://github.com/wtsi-npg/npg_seq_pipeline/pull/487
=> use cram files in adapter check

lib/npg_qc/autoqc/qc_store.pm
Forward compatibility with https://github.com/wtsi-npg/npg_tracking/pull/528 and https://github.com/wtsi-npg/npg_tracking/pull/530
=> targeted error capture

Changes, lib/npg_qc/autoqc/checks/check.pm, lib/npg_qc/autoqc/checks/rna_seqc.pm, lib/npg_qc/autoqc/results/base.pm, lib/npg_qc/autoqc/results/result.pm, lib/npg_qc/autoqc/role/result.pm, lib/npg_qc/utils/genotype_calling.pm, t/60-autoqc-autoqc.t, t/60-autoqc-checks-bam_flagstats.t, t/60-autoqc-checks-check.t, t/60-autoqc-results-base.t, t/60-autoqc-results-result.t, t/60-autoqc-results-samtools_stats.t, t/60-autoqc-results-spatial_filter.t, t/60-autoqc-results-tag_decode_stats.t
Depends on https://github.com/wtsi-npg/npg_tracking/pull/549
=> standard file names for JSON results and arrays of results

Changes, lib/npg_qc/Schema/Result/Review.pm, lib/npg_qc/autoqc/checks/review.pm, lib/npg_qc/autoqc/results/review.pm, lib/npg_qc/autoqc/role/result.pm, t/50-schema-result-Review.t, t/60-autoqc-checks-review.t, t/60-autoqc-db_loader.t, t/60-autoqc-results-result.t, t/60-autoqc-results-review.t
This is a prerequisite for https://github.com/wtsi-npg/npg_qc/pull/667
=> review check - criteria md5 availability

README_QC.md
=> QC explained

Changes, MANIFEST, bin/npg_simple_robo4artic, lib/npg_qc/Schema/Mqc/OutcomeEntity.pm, lib/npg_qc/autoqc/checks/review.pm, t/60-autoqc-checks-review.t
Example usage
cat PATH_TO_RUNFOLDER/Latest_Summary/../pp_archive/lane{1,2}/plex*/ncov2019_artic_nf/v0.1.0/34014.qc.csv | grep -v sample_name | npg_simple_robo4artic
=> robo script for artic QC data

t/data/reporter/mlwarehouse/400-IseqFlowcell.yml
To conform with https://github.com/wtsi-npg/ml_warehouse/pull/143
=> db fixture update to conform with a new unique constraint

Changes, MANIFEST, lib/npg_qc/Schema/Result/Generic.pm, lib/npg_qc/autoqc/results/generic.pm, lib/npg_qc/autoqc/role/generic.pm, npg_qc_viewer/Build.PL, npg_qc_viewer/MANIFEST, npg_qc_viewer/lib/npg_qc_viewer/Model/Check.pm, npg_qc_viewer/root/src/ui_checks/generic.tt2, npg_qc_viewer/root/src/ui_lanes/library_lanes.tt2, scripts/upgrade_schema/upgrade_schema-68.6.0, t/50-schema-result-Generic.t, t/60-autoqc-results-generic.t
Built on top of https://github.com/wtsi-npg/npg_qc/pull/698
=> Seqqc4generic

Changes, MANIFEST, bin/npg_autoqc_generic4artic, lib/npg_qc/Schema/Result/Generic.pm, lib/npg_qc/autoqc/results/generic.pm, lib/npg_qc/autoqc/role/generic.pm, scripts/upgrade_schema/upgrade_schema-68.6.0, t/50-schema-result-Generic.t, t/60-autoqc-results-generic.t
Incorporates https://github.com/wtsi-npg/npg_qc/pull/698
=> script for generic: base control type/real sample assessment on LIMs flags

npg_qc_viewer/root/src/ui_checks/generic.tt2, npg_qc_viewer/root/src/ui_checks/rna_seqc.tt2, npg_qc_viewer/root/src/ui_lanes/library_lanes.tt2
=> Ampliconstats images display

npg_qc_viewer/root/src/ui_checks/rna_seqc.tt2, npg_qc_viewer/root/src/ui_lanes/library_lanes.tt2
Tested with the viewer, works as expected.
=> rna_seq template simplification and db access optimisation

Build.PL, lib/npg_qc/autoqc/role/generic.pm, npg_qc_viewer/Build.PL, npg_qc_viewer/root/src/ui_checks/generic.tt2, t/60-autoqc-results-generic.t
Implementing simple JSON formatting for Generic QC. Making a lot of assumptions about how non-generic Generic is.
=> Implement ncov1029-artic-nf specific render-behaviour in Generic type

lib/npg_qc/autoqc/role/result.pm, t/60-autoqc-checks-check.t
also tests amended in accordance with https://github.com/wtsi-npg/npg_tracking/pull/602
=> disable a check for circular references in serialization

.github/workflows/testing_and_building_repos.yml
Resolving issues #755 and #754 .
=> Remove redundant PATH setting from Action config

Changes, npg_qc_viewer/bower.json
Waiting for https://github.com/wtsi-npg/bcviz/pull/67 to reach master
=> switch to bcviz@1.3.3

Changes, bin/npg_substitution_metrics.pl, lib/npg_qc/utils/bam_genotype.pm
=> prep release 70.0.1

.github/workflows/testing_and_building_repos.yml
Add apt-get update before package installation
Add libgd-text-perl
=> Fix libgd OS package dependency

bin/call_gtck_composite_rpt.pl
This part contained the code that failed the compilation following the deletion of teh short_info role in
https://github.com/wtsi-npg/npg_tracking/pull/812
=> Removed an unused part of the script.

Changes, MANIFEST, lib/npg_qc/autoqc/checks/review.pm, t/60-autoqc-checks-review.t, t/data/autoqc/191210_MS2_MiSeq_walk-up_246_A_MS8539685-050V2/RunParameters.xml, t/data/autoqc/review/mqc_type/product_release.yml, t/data/autoqc/review/no_applicability4single/product_release.yml, t/data/autoqc/review/product_release.yml
Built on top of https://github.com/wtsi-npg/npg_qc/pull/869
=> Add robo sequencing_run applicability criteria type

npg_qc_viewer/README
Want to explain co-located means they are under the same DNS entry. They could be in different hosts as long as you reach both hosts with the same name (DNS).
=> small edits for seqqc readme

Changes, lib/npg_qc/autoqc/checks/review.pm, t/60-autoqc-checks-review.t, t/data/runfolder_49285/product_release.yml
Updated the expression evaluator to allow for multiple types of result objects to be used in a single expression.
=> Updated the expression evaluator.

lib/npg_qc/illumina/interop/parser.pm
add optional tile limits (first tile, tile count) to Illumina interop files parsing
=> add optional tile limits to Illumina interop files parsing
